// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement = "CgkIlcrLvLgNEAIQCw"; // <GPGSID> 튜토리얼
        public const string achievement__1 = "CgkIlcrLvLgNEAIQBA"; // <GPGSID> 1 스테이지
        public const string achievement__2 = "CgkIlcrLvLgNEAIQBQ"; // <GPGSID> 2 스테이지
        public const string achievement__3 = "CgkIlcrLvLgNEAIQBg"; // <GPGSID> 3 스테이지
        public const string achievement__4 = "CgkIlcrLvLgNEAIQBw"; // <GPGSID> 4 스테이지
        public const string achievement_2 = "CgkIlcrLvLgNEAIQCA"; // <GPGSID> 도전 스테이지
        public const string achievement_3 = "CgkIlcrLvLgNEAIQAg"; // <GPGSID> 스테이지 올 클리어
        public const string achievement_4 = "CgkIlcrLvLgNEAIQAw"; // <GPGSID> 부자
        public const string achievement_5 = "CgkIlcrLvLgNEAIQCg"; // <GPGSID> 발로해도..
        public const string achievement_6 = "CgkIlcrLvLgNEAIQCQ"; // <GPGSID> 실패자

}

